---
- name: WSL with Ubuntu 24.04
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  roles:
    - ansible
    - homebrew
    - docker
    - zsh
    - packages
    - dotfiles
