---
- name: Ensure old versions of Docker are not installed
  ansible.builtin.package:
    name: "{{ docker_obsolete_packages }}"
    state: absent
- name: Ensure directory exists for /etc/apt/keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
- name: Add Docker repository
  block:
    - name: Add Docker repository | apt key
      ansible.builtin.get_url:
        url: "{{ docker_apt_gpg_key }}"
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: false
        checksum: "{{ docker_apt_gpg_key_checksum | default(omit) }}"
      when: docker_add_repo
    - name: Add Docker repository | apt source
      ansible.builtin.apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: present
        filename: "{{ docker_apt_filename }}"
        update_cache: true
      when: docker_add_repo
